### ISSUE TITLE
Keep imports in order

### ISSUE THREAD

**Issue by AlisCode** [impero-com/ts_export#10]
When outputting the exports, we take care that they get exported in the same order that the tool receives them. This makes sure that when generating the TS bindings for the same Rust source module two times in a row, you get the exact same output.

The imports, on the other hand, don't follow a specific order, and may vary depending on the mood of the HashMap. We need to sort the imports before outputting them to the file.

**Comment by greyblake** [comment]
For ordered key-value collection [indexmap::IndexMap](https://docs.rs/indexmap/1.6.1/indexmap/map/struct.IndexMap.html) does the job

**Comment by greyblake** [comment]
@AlisCode Please see https://github.com/impero-com/ts_export/pull/12

**Comment by AlisCode** [comment]
I merged before actually testing that this would solve the problem. It seems like this isnt the case (after testing, I had two different output files for the same input file).

I suggest actually sorting the imports before outputting.
