### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by AlisCode** [impero-com/ts_export#6]
We need to find a cool name for this project, ts_export is a bit bland to say the least. 

# Ideas  

Initial braimstorming lead to those ideas (unranked)

* `downgrader` - because we're "downgrading" from Rust's strict typing to a more flexible type system. I'm hoping not to offend anyone in the TS community with this. 
* `typescriptify`- but that's already taken of course so no dice
* `rs2ts` - but `rsts` is already taken 
* `libraryThatGetsRustTypesAndTranformThemIntoTypescriptTypes` - or `TypeScriptFactoryBean`
* `rustys` for RusTypescript
* `roustons` - no justification given
* `armaggedon` - no justification given
* `typeksporti` - Esperanto for "type export(ing)"

Once we choose something that looks fine, rename all crates to that. We might want to whip out Inkscape and create a silly logo  whenever we have time.

**Comment by greyblake** [comment]
I think it's like in business. There must be ether a strong brand name or  a name should give a hint about want a business does.

In this sense I think name should refer somehow to "typescript". 
Although `typescriptify` is taken, we can consider `typescripted` instead.

**Comment by AlisCode** [comment]
I suggest `typebinder`. 

It creates bindings for your types, and is agnostic with regards to the output format. We only support `TypeScript` as a target for now, but we might want to modularize this crate even more to support other languages or other types of exports in the future. Use case includes : 

* Auto-generating a client for your Web Framework (using `axios` or regular JS' `fetch`)
* Auto-generating bindings for Python, Java, ... Though this gets limited by the type-system capabilities of the target (*e.g.* C has very limited/no support for generics, not in the Rust way anyway). 

I'm not sure on how to decide the name of this project, it seems for now I'm the one in charge so if no better idea is given by the time I release this to crates.io, I'll be rebranding this project to that.

**Comment by greyblake** [comment]
@AlisCode Did you consider other sources than Rust as well? If so we may need something like intermediate type representation.

**Comment by AlisCode** [comment]
@greyblake Non-Rust input isn't a goal of this project anytime soon. Would make things a bit more complex haha

**Comment by AlisCode** [comment]
Settled on `typebinder` for now. I like it.
